public enum Edge_Position {
	ONE_ONE, ONE_TWO, ONE_THREE, ONE_FOUR, ONE_FIVE, TWO_ONE,
	TWO_TWO, TWO_THREE, TWO_FOUR, TWO_FIVE, TWO_SIX, TWO_SEVEN,
	TWO_EIGHT, TWO_NINE, TWO_TEN, TWO_ELEVEN,TWO_THIRTEEN, TWO_FOURTEEN,
	TWO_FIFTEEN, THREE_ONE, THREE_TWO, THREE_THREE, THREE_FOUR, THREE_FIVE,
}
